## Preparação dos dados

### importando bibliotecas

In [100]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### importando os dados

In [101]:
train = pd.read_csv('train.csv')
test_set = pd.read_csv('test.csv')

### visualizando os dados

In [102]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [103]:
train.describe().transpose()

count        mean         std   min       25%       50%    75%  \
PassengerId  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5   
Survived     891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0   
Pclass       891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0   
Age          714.0   29.699118   14.526497  0.42   20.1250   28.0000   38.0   
SibSp        891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0   
Parch        891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0   
Fare         891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

In [104]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### Preenchendo colunas com valores NA

In [105]:
train.Embarked.fillna(train['Embarked'].value_counts().index[0],inplace=True)
train.Age.fillna(train.Age.median(), inplace=True)

### criando novas variáveis

In [106]:
import re

def nomes(dados):
    def extract_title(name):
        title_search = re.search(' ([A-Za-z]+)\.', name)
    # If the title exists, extract and return it.
        if title_search:
            return title_search.group(1)
        return ""
    dados['Title'] = dados['Name'].apply(extract_title)
    dados['Title'] = dados['Title'].replace(['Lady', 'Countess','Capt', 'Col','Don','Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
    dados['Title'] = dados['Title'].replace('Mlle', 'Miss')
    dados['Title'] = dados['Title'].replace('Ms', 'Miss')
    dados['Title'] = dados['Title'].replace('Mme', 'Mrs')
    return(dados)

In [107]:
def variaveis(dados):
    dados['FamilySize'] = dados['SibSp'] + dados['Parch'] + 1
    dados['Age_bin'] = pd.cut(dados['Age'], bins=[0,12,20,40,120], labels=['Children','Teenage','Adult','Elder'])
    dados['Fare_bin'] = pd.cut(dados['Fare'], bins=[-0.1,7.91,14.45,31,1000], labels=['Low_fare','median_fare','Average_fare','high_fare'])
    return(dados)

In [108]:
train = variaveis(train)
train = nomes(train)
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  FamilySize  Age_bin  \
0        0         A/5 21171   7.2500   NaN        S           2    Adult   
1        0          PC 17599  71.2833   C85        C           2    Adult   
2        0  STON/O2. 3101282   7.9250   NaN        S           1    Adult   
3        0            113803  53.1000  C123        S           2    Adult   
4        0            373450   8.0500   NaN        S           1    Adult   
..     ...               ...      ...   ...      ...         ...      ...   
886      0            211536  13.0000   NaN        S           1    Adult   
887      0            112053  30.0000   B42        S           1  Teenage   
888      2        W./C. 6607  23.4500   NaN        S           4    Adult   
889      0            111369  30.0000  C148        C           1    Adult   
890      0            370376   7.7500   NaN        Q           1    Adult   

         Fare_bin Title  
0        Low_fare    Mr  
1       high_fare   Mrs  
2     median_fare  Miss  
3       high_fare   Mrs  
4     median_fare    Mr  
..            ...   ...  
886   median_fare  Rare  
887  Average_fare  Miss  
888  Average_fare  Miss  
889  Average_fare    Mr  
890      Low_fare    Mr  

[891 rows x 16 columns]

### Separando as variaveis preditivas e variavel resposta

In [109]:
x_variables = ['Sex','Embarked','Pclass','Age_bin','Fare_bin','Title','SibSp','Parch','FamilySize']

In [110]:
X = train[x_variables].values
y = train['Survived'].values

### encoding das váriaveis categóricas

In [111]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

### separando dados de treino e validação

In [112]:
#np.random.seed(10)
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size = 0.3)

### feature scaling

In [113]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train[:, -3:])
X_train[:, -3:] = scaler.transform(X_train[:, -3:])
X_valid[:, -3:] = scaler.transform(X_valid[:, -3:])

## Modelos

### importandos libraries

In [114]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

### Pipeline para ver qual o melhor modelo

### Artificial Neural Network (ANN)

In [116]:
pipe_ANN = Pipeline([('classifier' , MLPClassifier(max_iter=2000)),])


param_grid_ANN = [
    {'classifier' : [MLPClassifier(max_iter=1000)],
    'classifier__hidden_layer_sizes': [(75,), (100,),(125,),(150,),(175,),(200,)],
    'classifier__activation': ['relu'],
    'classifier__solver': ['adam'],
    'classifier__alpha': [0.0001, 0.05],
    'classifier__learning_rate': ['constant']}
]

best_ANN = GridSearchCV(pipe_ANN, param_grid = param_grid_ANN, cv = 5, verbose=True, n_jobs=-1)

In [115]:
pipe_ANN = Pipeline([('classifier' , MLPClassifier(max_iter=2000)),])


param_grid_ANN = [
    {'classifier' : [MLPClassifier(max_iter=1000)],
    'classifier__hidden_layer_sizes': [(50,), (100,),(150,),(200,),(100,50),(100,100),(150,150),(200,150),(50,50,50),
                                      (50,100,50),(100,100,100),(150,100,150),(200,150,200)],
    'classifier__activation': ['relu'],
    'classifier__solver': ['sgd', 'adam'],
    'classifier__alpha': [0.0001, 0.05],
    'classifier__learning_rate': ['constant','adaptive']}
]

best_ANN = GridSearchCV(pipe_ANN, param_grid = param_grid_ANN, cv = 5, verbose=True, n_jobs=-1)

In [117]:
best_ANN.fit(X_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:  1.8min finished


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('classifier',
                                        MLPClassifier(max_iter=2000))]),
             n_jobs=-1,
             param_grid=[{'classifier': [MLPClassifier(alpha=0.05,
                                                       hidden_layer_sizes=(75,),
                                                       max_iter=1000)],
                          'classifier__activation': ['relu'],
                          'classifier__alpha': [0.0001, 0.05],
                          'classifier__hidden_layer_sizes': [(75,), (100,),
                                                             (125,), (150,),
                                                             (175,), (200,)],
                          'classifier__learning_rate': ['constant'],
                          'classifier__solver': ['adam']}],
             verbose=True)

In [118]:
best_ANN.best_estimator_

Pipeline(steps=[('classifier',
                 MLPClassifier(alpha=0.05, hidden_layer_sizes=(75,),
                               max_iter=1000))])

### treinando ANN

In [119]:
ANN = MLPClassifier(alpha=0.05, hidden_layer_sizes=(75,),
                               max_iter=1000)
ANN.fit(X_train, y_train)

MLPClassifier(alpha=0.05, hidden_layer_sizes=(75,), max_iter=1000)

In [120]:
y_pred_ANN = ANN.predict(X_valid)

In [121]:
cm_ANN = confusion_matrix(y_valid, y_pred_ANN)
print(cm_ANN)
accuracy_score(y_valid, y_pred_ANN)

[[141  13]
 [ 35  79]]


0.8208955223880597

In [122]:
accuracies_ANN = cross_val_score(estimator = ANN, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies_ANN.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_ANN.std()*100))

Accuracy: 80.42 %
Standard Deviation: 2.45 %


### Logistic Regression

In [123]:
pipe_LR = Pipeline([('classifier' , RandomForestClassifier()),])

# np.logspace(-4, 4, 20)
param_grid_LR = [
    {'classifier' : [LogisticRegression()],
     'classifier__penalty' : ['l1', 'l2','elasticnet'],
    'classifier__C' : list(np.arange(0.0001,5,0.2)),
    'classifier__solver' : ['liblinear','newton-cg','lbfgs','sag','saga']}]

best_LR = GridSearchCV(pipe_LR, param_grid = param_grid_LR, cv = 5, verbose=True, n_jobs=-1)

In [124]:
best_LR.fit(X_train,y_train)

Fitting 5 folds for each of 375 candidates, totalling 1875 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done 116 tasks      | elapsed:    0.9s
[Parallel(n_jobs=-1)]: Done 1875 out of 1875 | elapsed:    9.7s finished


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('classifier',
                                        RandomForestClassifier())]),
             n_jobs=-1,
             param_grid=[{'classifier': [LogisticRegression(C=1.2001000000000002,
                                                            penalty='l1',
                                                            solver='saga')],
                          'classifier__C': [0.0001, 0.2001, 0.4001,
                                            0.6001000000000001, 0.8001, 1.0001,
                                            1.2001000000000002,
                                            1.4001000000000001, 1.6001, 1.8001,
                                            2.0001, 2.2001000000000004,
                                            2.4001000000000006,
                                            2.6001000000000003,
                                            2.8001000000000005, 3.0001,
                                     

In [125]:
best_LR.best_estimator_

Pipeline(steps=[('classifier',
                 LogisticRegression(C=1.2001000000000002, penalty='l1',
                                    solver='saga'))])

### Treinando Logistic Regression

In [126]:
LR = LogisticRegression(max_iter=10000,C=1.2001000000000002, penalty='l1',
                                    solver='saga')
LR.fit(X_train, y_train)

LogisticRegression(C=1.2001000000000002, max_iter=10000, penalty='l1',
                   solver='saga')

In [127]:
y_pred_LR = LR.predict(X_valid)

In [128]:
cm_LR = confusion_matrix(y_valid, y_pred_LR)
print(cm_LR)
accuracy_score(y_valid, y_pred_LR)

[[138  16]
 [ 30  84]]


0.8283582089552238

In [129]:
accuracies_LR = cross_val_score(estimator = LR, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies_LR.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_LR.std()*100))

Accuracy: 81.23 %
Standard Deviation: 3.42 %


### Random Forest

In [130]:
pipe_RF = Pipeline([('Classifier' , RandomForestClassifier()),])

param_grid_RF = [
    {'Classifier__criterion' : ['gini','entropy'],
    'Classifier__n_estimators' : list(range(10,101,10)),
    'Classifier__max_features' : ['sqrt','log2']}
]

best_RF = GridSearchCV(pipe_RF, param_grid = param_grid_RF, cv = 5, verbose=True, n_jobs=-1)

In [131]:
best_RF.fit(X_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  76 tasks      | elapsed:    4.5s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:   13.1s finished


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('Classifier',
                                        RandomForestClassifier())]),
             n_jobs=-1,
             param_grid=[{'Classifier__criterion': ['gini', 'entropy'],
                          'Classifier__max_features': ['sqrt', 'log2'],
                          'Classifier__n_estimators': [10, 20, 30, 40, 50, 60,
                                                       70, 80, 90, 100]}],
             verbose=True)

In [132]:
best_RF.best_estimator_

Pipeline(steps=[('Classifier', RandomForestClassifier(max_features='sqrt'))])

### Treinando Random Forest

In [133]:
RF = RandomForestClassifier(max_features='sqrt')
RF.fit(X_train, y_train)

RandomForestClassifier(max_features='sqrt')

In [134]:
y_pred_RF = RF.predict(X_valid)

In [135]:
cm_RF = confusion_matrix(y_valid, y_pred_RF)
print(cm_RF)
accuracy_score(y_valid, y_pred_RF)

[[142  12]
 [ 36  78]]


0.8208955223880597

In [136]:
accuracies_RF = cross_val_score(estimator = RF, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies_RF.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_RF.std()*100))

Accuracy: 80.41 %
Standard Deviation: 2.87 %


## Support Vector Classification (SVC)

In [137]:
pipe_SVC = Pipeline([('Classifier' , SVC()),])

param_grid_SVC = [{
    'Classifier__kernel' : ['poly','rbf','sigmoid','linear'],
    'Classifier__C' : list(np.arange(0.0001,5,0.2)),
    'Classifier__gamma' : ['scale','auto']}
]

best_SVC = GridSearchCV(pipe_SVC, param_grid = param_grid_SVC, cv = 5, verbose=True, n_jobs=-1)

In [138]:
best_SVC.fit(X_train,y_train)

Fitting 5 folds for each of 200 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done 200 tasks      | elapsed:    1.4s
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:    6.6s finished


GridSearchCV(cv=5, estimator=Pipeline(steps=[('Classifier', SVC())]), n_jobs=-1,
             param_grid=[{'Classifier__C': [0.0001, 0.2001, 0.4001,
                                            0.6001000000000001, 0.8001, 1.0001,
                                            1.2001000000000002,
                                            1.4001000000000001, 1.6001, 1.8001,
                                            2.0001, 2.2001000000000004,
                                            2.4001000000000006,
                                            2.6001000000000003,
                                            2.8001000000000005, 3.0001,
                                            3.2001000000000004,
                                            3.4001000000000006,
                                            3.6001000000000003,
                                            3.8001000000000005, 4.0001, 4.2001,
                                            4.4001, 4.6001,
                       

In [139]:
best_SVC.best_estimator_

Pipeline(steps=[('Classifier', SVC(C=3.4001000000000006, gamma='auto'))])

### Treinando SVC

In [140]:
SVC = SVC(C=3.4001000000000006, gamma='auto')
SVC.fit(X_train, y_train)

SVC(C=3.4001000000000006, gamma='auto')

In [141]:
y_pred_SVC = SVC.predict(X_valid)

In [142]:
cm_SVC = confusion_matrix(y_valid, y_pred_SVC)
print(cm_SVC)
accuracy_score(y_valid, y_pred_SVC)

[[138  16]
 [ 28  86]]


0.835820895522388

In [143]:
accuracies_SVC = cross_val_score(estimator = SVC, X = X_train, y = y_train, cv = 6)
print("Accuracy: {:.2f} %".format(accuracies_SVC.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_SVC.std()*100))

Accuracy: 82.19 %
Standard Deviation: 2.50 %


### xgboost

In [ ]:
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

In [ ]:
y_pred_xgb = xgb.predict(X_valid)
cm_xgb = confusion_matrix(y_valid, y_pred_xgb)
print(cm_xgb)
accuracy_score(y_valid, y_pred_xgb)

In [ ]:
accuracies_xgb = cross_val_score(estimator = xgb, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies_xgb.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_xgb.std()*100))

## stacking model

In [144]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

estimator_list = [
    ('ann',ANN),
    ('SVC',SVC),
    ('LR',LR)]

# Build stack model
stack_model = StackingClassifier(
    estimators=estimator_list, final_estimator=LogisticRegression()
)

# Train stacked model
stack_model.fit(X_train, y_train)

StackingClassifier(estimators=[('ann',
                                MLPClassifier(alpha=0.05,
                                              hidden_layer_sizes=(75,),
                                              max_iter=1000)),
                               ('SVC', SVC(C=3.4001000000000006, gamma='auto')),
                               ('LR',
                                LogisticRegression(C=1.2001000000000002,
                                                   max_iter=10000, penalty='l1',
                                                   solver='saga'))],
                   final_estimator=LogisticRegression())

In [145]:
y_pred_stack_model = stack_model.predict(X_valid)
cm_stack_model = confusion_matrix(y_valid, y_pred_stack_model)
print(cm_stack_model)
accuracy_score(y_valid, y_pred_stack_model)

[[138  16]
 [ 28  86]]


0.835820895522388

In [146]:
accuracies_stack_model = cross_val_score(estimator = stack_model, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies_stack_model.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_stack_model.std()*100))

Accuracy: 81.71 %
Standard Deviation: 2.93 %


### criando submissão

### treinar para toda base de dados

In [ ]:
X[:, -3:] = scaler.transform(X[:, -3:])

In [ ]:
X

In [ ]:
ann.fit(X, y)

### processando os dados de teste

In [86]:
test_set.Embarked.fillna(train['Embarked'].value_counts().index[0],inplace=True)
test_set.Age.fillna(test_set.Age.median(), inplace=True)
test_set.Fare.fillna(test_set.Fare.median(), inplace=True)

In [87]:
test_set = variaveis(test_set)
test_set = nomes(test_set)

In [88]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   PassengerId  418 non-null    int64   
 1   Pclass       418 non-null    int64   
 2   Name         418 non-null    object  
 3   Sex          418 non-null    object  
 4   Age          418 non-null    float64 
 5   SibSp        418 non-null    int64   
 6   Parch        418 non-null    int64   
 7   Ticket       418 non-null    object  
 8   Fare         418 non-null    float64 
 9   Cabin        91 non-null     object  
 10  Embarked     418 non-null    object  
 11  FamilySize   418 non-null    int64   
 12  Age_bin      418 non-null    category
 13  Fare_bin     418 non-null    category
 14  Title        418 non-null    object  
dtypes: category(2), float64(2), int64(5), object(6)
memory usage: 43.8+ KB


In [89]:
X_test = test_set[x_variables].values

In [90]:
X_test = np.array(ct.transform(X_test))

In [91]:
X_test[:, -3:] = scaler.transform(X_test[:, -3:])

In [150]:
pred_test = RF.predict(X_test)

## Criando a submissão

In [151]:
sub = pd.Series(pred_test, index=test_set['PassengerId'], name='Survived')
sub

PassengerId
892     0
893     1
894     0
895     0
896     1
       ..
1305    0
1306    1
1307    0
1308    0
1309    1
Name: Survived, Length: 418, dtype: int64

In [152]:
sub.to_csv("RF_sub.csv", header=True)